### ISSUE TITLE
关于安装方式

### ISSUE THREAD

**Issue by huigang39** [lxgw/LxgwNeoXiHei#13]
能否添加使用scoop的安装方式，毕竟霞鹜文楷也可以通过scoop安装和更新。

**Comment by lxgw** [comment]
「霞鹜文楷」的 scoop 是由他人维护，而非本人维护。如果有人维护了这款字体的 scoop 安装方式，烦请 pull request。

**Comment by huigang39** [comment]
> 「霞鹜文楷」的 scoop 是由他人维护，而非本人维护。如果有人维护了这款字体的 scoop 安装方式，烦请 pull request。

好的，明白，谢了。
