### ISSUE TITLE
v1.124 版本部分日语文本出现乱码

### ISSUE THREAD

**Issue by happybrisk** [lxgw/LxgwNeoXiHei#14]
- 使用字体：霞鹜新晰黑 屏幕阅读版 `LXGWNeoXiHeiScreen.ttf`
- 现象：在浏览器中指定字体后，部分文字（假名）出现乱码。在 Word（Mac）中正常。

截图：

v1.123.2（正常）：
![image](https://github.com/user-attachments/assets/ecd122dc-acd6-4812-8144-bf9be4776447)

v1.124（异常）：
![image](https://github.com/user-attachments/assets/50d9b75b-dd16-4d39-a140-2423a6feb959)

**Comment by lxgw** [comment]
目前还不知道这个问题出在哪里，所以无法复现。您可以继续使用旧版字体。

**Comment by lxgw** [comment]
![QQ_1721988932354](https://github.com/user-attachments/assets/7e8087cb-cae6-4005-a511-4ad177c077fd)

Windows 11，Edge 下显示正常。

**Comment by happybrisk** [comment]
好的，我回去用 Windows 11 系统试试。

**Comment by lxgw** [comment]
Xubuntu 22.04，LibreOffice Writer，问题复现。

![3e1fc9e2711e66f3a4ea0c64f663375b](https://github.com/user-attachments/assets/ed3bad2d-f4a1-4cf5-b008-a6a0a3308601)

**Comment by lxgw** [comment]
https://github.com/lxgw/LxgwNeoXiHei-Screen/releases/tag/v1.190-beta.1 您可以试试这个版本。

**Comment by happybrisk** [comment]
> https://github.com/lxgw/LxgwNeoXiHei-Screen/releases/tag/v1.190-beta.1 您可以试试这个版本。

感谢，Mac 下这个版本正常了。

![image](https://github.com/user-attachments/assets/49d9d619-8d4d-4a52-b1a0-f1091ddd0d36)
